BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB
    XXX XX
BBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX
    XXXXXX
    XXXXXXX
BBBBBBBB
