BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB
    XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXX XXX XXXX XXX XXXX XX XXX XXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXXXX
BBBBBBBB