BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB
    XXXX XX
BBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX
    XXXXXXX
BBBBBBBB
